- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - core
- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - core
- name: Install System Packages 3 (stow, xclip, ripgrep)
  apt:
    name: [ "stow", "xclip", "ripgrep"]
  tags:
    - install
    - core
- name: Install fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git" 
    dest: "~/.fzf"
  tags:
    - install
    - core
- name: Install fzf (shell)
  shell: ~/.fzf/install
  tags:
    - install
    - core
