- name: Download neovim
  shell: "curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage && chmod u+x nvim.appimage"
  tags:
    - neovim
- name: Extract neovim
  shell: "./nvim.appimage --appimage-extract && ./squashfs-root/AppRun --version"
  tags:
    - neovim
- name: Move and SymLink neovim
  shell: "mv squashfs-root / && ln -s /squashfs-root/AppRun /usr/bin/nvim"
  tags:
    - neovim
- name: Clone Packer 
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - neovim
