- name: Install zsh
  apt: name=zsh
  tags:
    - core
    - zsh
- name: Change shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
    - core
- name: Install ohmyzsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - zsh
    - core
- name: Install plugin for Auto Suggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
    - core
- name: Download honukai theme
  shell: curl -L https://raw.githubusercontent.com/oskarkrawczyk/honukai-iterm-zsh/tree/master/honukai.zsh-theme > ~/.oh-my-zsh/themes/honukai.zsh-theme
  tags:
    - zsh
    - core
